#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hackathon_ICICI.Resource", IsApplication=true)]

namespace Hackathon_ICICI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.TextToSpeech.Resource.String.ApplicationName = global::Hackathon_ICICI.Resource.String.ApplicationName;
			global::Plugin.TextToSpeech.Resource.String.Hello = global::Hackathon_ICICI.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accountdetails = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backbutton1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bankatm = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg11 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg21 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg4 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg5 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg6 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg7 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg8 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg9 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int billpayment = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int carddetails = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int creditcard = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int debitcard = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int easeofaccess = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int fundtransfer = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icicibanner = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int icicilogo1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icicilogobeveled1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icicilogosolo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int information2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int loginicon2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int loginiconsolo = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int pelogo1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int personaldetails2 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int personaldetailssolo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int powerbutton = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roundedButton = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundedButtondark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roundedEditText = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int services = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int signin2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int signinsolo = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int splashAdjustment = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int splashscreen = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int transactionhistory = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int accountBalance = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int accountCustomerID = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int accountLabel2 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int accountLabel3 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int accountLabel5 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int accountLabel6 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int accountLabel7 = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int accountName = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int accountNumber = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int accountPhone = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int accountStatus = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int accountType = 2131165196;
			
			// aapt resource value: 0x7f07001b
			public const int billAmount = 2131165211;
			
			// aapt resource value: 0x7f070012
			public const int billBack = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int billCustID = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int billIcon = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int billLabel1 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int billLabel2 = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int billLabel4 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int billLabel5 = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int billNickname = 2131165209;
			
			// aapt resource value: 0x7f070022
			public const int branchDetailATM = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int branchDetailBank = 2131165219;
			
			// aapt resource value: 0x7f07002a
			public const int branchDetailsAdd = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int branchDetailsCity = 2131165227;
			
			// aapt resource value: 0x7f070029
			public const int branchDetailsIFSC = 2131165225;
			
			// aapt resource value: 0x7f070020
			public const int branchDetailsLabel1 = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int branchDetailsLabel3 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int branchDetailsLabel4 = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int branchDetailsLabel5 = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int branchDetailsName = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int branchDetailsPhone = 2131165224;
			
			// aapt resource value: 0x7f070010
			public const int button1 = 2131165200;
			
			// aapt resource value: 0x7f07002d
			public const int cardCreditCard = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int cardDebitCard = 2131165228;
			
			// aapt resource value: 0x7f07002f
			public const int creditAccountNumber = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int creditCardNumber = 2131165233;
			
			// aapt resource value: 0x7f070037
			public const int creditCardStatus = 2131165239;
			
			// aapt resource value: 0x7f070033
			public const int creditCardType2 = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int creditExpiry = 2131165237;
			
			// aapt resource value: 0x7f07002e
			public const int creditLabel2 = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int creditLabel3 = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int creditLabel5 = 2131165234;
			
			// aapt resource value: 0x7f070034
			public const int creditLabel6 = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int creditLabel7 = 2131165238;
			
			// aapt resource value: 0x7f070057
			public const int datePicker1 = 2131165271;
			
			// aapt resource value: 0x7f070039
			public const int debitAccountNumber = 2131165241;
			
			// aapt resource value: 0x7f07003b
			public const int debitCardNumber = 2131165243;
			
			// aapt resource value: 0x7f07003d
			public const int debitCardType2 = 2131165245;
			
			// aapt resource value: 0x7f07003f
			public const int debitExpiry = 2131165247;
			
			// aapt resource value: 0x7f070038
			public const int debitLabel2 = 2131165240;
			
			// aapt resource value: 0x7f07003a
			public const int debitLabel3 = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int debitLabel5 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int debitLabel6 = 2131165246;
			
			// aapt resource value: 0x7f07007b
			public const int editText1 = 2131165307;
			
			// aapt resource value: 0x7f070075
			public const int editText2 = 2131165301;
			
			// aapt resource value: 0x7f07001c
			public const int finalSubmitButton = 2131165212;
			
			// aapt resource value: 0x7f070041
			public const int fundAccNumber = 2131165249;
			
			// aapt resource value: 0x7f070045
			public const int fundAmount = 2131165253;
			
			// aapt resource value: 0x7f070051
			public const int fundCompleteAmount = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int fundCompleteDate = 2131165267;
			
			// aapt resource value: 0x7f07004d
			public const int fundCompleteDest = 2131165261;
			
			// aapt resource value: 0x7f07004a
			public const int fundCompleteLabel1 = 2131165258;
			
			// aapt resource value: 0x7f07004c
			public const int fundCompleteLabel2 = 2131165260;
			
			// aapt resource value: 0x7f07004e
			public const int fundCompleteLabel3 = 2131165262;
			
			// aapt resource value: 0x7f070050
			public const int fundCompleteLabel4 = 2131165264;
			
			// aapt resource value: 0x7f070052
			public const int fundCompleteLabel5 = 2131165266;
			
			// aapt resource value: 0x7f07004f
			public const int fundCompletePayee = 2131165263;
			
			// aapt resource value: 0x7f07004b
			public const int fundCompleteRefID = 2131165259;
			
			// aapt resource value: 0x7f070043
			public const int fundDestAccount = 2131165251;
			
			// aapt resource value: 0x7f070055
			public const int fundExit = 2131165269;
			
			// aapt resource value: 0x7f070040
			public const int fundLabel1 = 2131165248;
			
			// aapt resource value: 0x7f070054
			public const int fundTransferComplete = 2131165268;
			
			// aapt resource value: 0x7f070046
			public const int fundTransferSubmit = 2131165254;
			
			// aapt resource value: 0x7f070044
			public const int fundlabel3 = 2131165252;
			
			// aapt resource value: 0x7f070064
			public const int iciciATM = 2131165284;
			
			// aapt resource value: 0x7f070060
			public const int iciciLogo = 2131165280;
			
			// aapt resource value: 0x7f070001
			public const int imageButton1 = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int imageButton2 = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int imageView1 = 2131165187;
			
			// aapt resource value: 0x7f07005e
			public const int imageView2 = 2131165278;
			
			// aapt resource value: 0x7f070065
			public const int imageView5 = 2131165285;
			
			// aapt resource value: 0x7f070056
			public const int intervalLabel1 = 2131165270;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout2 = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout3 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout4 = 2131165214;
			
			// aapt resource value: 0x7f070047
			public const int linearLayout5 = 2131165255;
			
			// aapt resource value: 0x7f070063
			public const int linearLayout6 = 2131165283;
			
			// aapt resource value: 0x7f070087
			public const int linearLayout7 = 2131165319;
			
			// aapt resource value: 0x7f070074
			public const int linearLayout8 = 2131165300;
			
			// aapt resource value: 0x7f07005a
			public const int loginCustID = 2131165274;
			
			// aapt resource value: 0x7f070059
			public const int loginLabel1 = 2131165273;
			
			// aapt resource value: 0x7f07005b
			public const int loginLabel4 = 2131165275;
			
			// aapt resource value: 0x7f07005d
			public const int loginSubmit = 2131165277;
			
			// aapt resource value: 0x7f070058
			public const int loginlabel3 = 2131165272;
			
			// aapt resource value: 0x7f070061
			public const int mainLogin = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int mainSignup = 2131165282;
			
			// aapt resource value: 0x7f07009a
			public const int miniBack = 2131165338;
			
			// aapt resource value: 0x7f070066
			public const int miniStatementBack = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int miniStatementLabel2 = 2131165287;
			
			// aapt resource value: 0x7f070069
			public const int miniStatementLabel3 = 2131165289;
			
			// aapt resource value: 0x7f07006b
			public const int miniStatementLabel4 = 2131165291;
			
			// aapt resource value: 0x7f07006d
			public const int miniStatementLabel5 = 2131165293;
			
			// aapt resource value: 0x7f07006f
			public const int miniStatementLabel6 = 2131165295;
			
			// aapt resource value: 0x7f070071
			public const int miniStatementLabel7 = 2131165297;
			
			// aapt resource value: 0x7f07005c
			public const int otpbox = 2131165276;
			
			// aapt resource value: 0x7f07005f
			public const int peLogo = 2131165279;
			
			// aapt resource value: 0x7f070077
			public const int personalAge = 2131165303;
			
			// aapt resource value: 0x7f070073
			public const int personalBack = 2131165299;
			
			// aapt resource value: 0x7f07007d
			public const int personalGender = 2131165309;
			
			// aapt resource value: 0x7f07007a
			public const int personalLabelAddress = 2131165306;
			
			// aapt resource value: 0x7f070076
			public const int personalLabelAge = 2131165302;
			
			// aapt resource value: 0x7f07007c
			public const int personalLabelGender = 2131165308;
			
			// aapt resource value: 0x7f070081
			public const int personalLabelMarital = 2131165313;
			
			// aapt resource value: 0x7f070078
			public const int personalLabelPhone = 2131165304;
			
			// aapt resource value: 0x7f070085
			public const int personalLabelSegment = 2131165317;
			
			// aapt resource value: 0x7f070082
			public const int personalMarital = 2131165314;
			
			// aapt resource value: 0x7f070079
			public const int personalPhone = 2131165305;
			
			// aapt resource value: 0x7f070086
			public const int personalSegment = 2131165318;
			
			// aapt resource value: 0x7f070021
			public const int radioGroup1 = 2131165217;
			
			// aapt resource value: 0x7f07008e
			public const int serviceAccount = 2131165326;
			
			// aapt resource value: 0x7f07008d
			public const int serviceBill = 2131165325;
			
			// aapt resource value: 0x7f070090
			public const int serviceBranch = 2131165328;
			
			// aapt resource value: 0x7f07008b
			public const int serviceCard = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int serviceFund = 2131165324;
			
			// aapt resource value: 0x7f07008a
			public const int servicePersonal = 2131165322;
			
			// aapt resource value: 0x7f070088
			public const int serviceText = 2131165320;
			
			// aapt resource value: 0x7f07008f
			public const int serviceTransaction = 2131165327;
			
			// aapt resource value: 0x7f070089
			public const int servicesLogo = 2131165321;
			
			// aapt resource value: 0x7f070094
			public const int signUpAccountNumber = 2131165332;
			
			// aapt resource value: 0x7f070092
			public const int signUpCustID = 2131165330;
			
			// aapt resource value: 0x7f070091
			public const int signUpLabelCustomer = 2131165329;
			
			// aapt resource value: 0x7f070096
			public const int signUpLabelOTP = 2131165334;
			
			// aapt resource value: 0x7f070093
			public const int signUpLabelPhone = 2131165331;
			
			// aapt resource value: 0x7f070097
			public const int signUpOTP = 2131165335;
			
			// aapt resource value: 0x7f070098
			public const int signUpSubmit = 2131165336;
			
			// aapt resource value: 0x7f070095
			public const int signUpVerifyPhone = 2131165333;
			
			// aapt resource value: 0x7f07007e
			public const int space1 = 2131165310;
			
			// aapt resource value: 0x7f07007f
			public const int space2 = 2131165311;
			
			// aapt resource value: 0x7f070084
			public const int space3 = 2131165316;
			
			// aapt resource value: 0x7f070080
			public const int space4 = 2131165312;
			
			// aapt resource value: 0x7f070083
			public const int space5 = 2131165315;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f07001f
			public const int textView2 = 2131165215;
			
			// aapt resource value: 0x7f070042
			public const int textView3 = 2131165250;
			
			// aapt resource value: 0x7f070048
			public const int textView4 = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int textView5 = 2131165257;
			
			// aapt resource value: 0x7f07006c
			public const int transactionAccount = 2131165292;
			
			// aapt resource value: 0x7f070068
			public const int transactionAmount = 2131165288;
			
			// aapt resource value: 0x7f070072
			public const int transactionClosingBalance = 2131165298;
			
			// aapt resource value: 0x7f07006e
			public const int transactionCreditDebit = 2131165294;
			
			// aapt resource value: 0x7f07006a
			public const int transactionDate = 2131165290;
			
			// aapt resource value: 0x7f070099
			public const int transactionMini = 2131165337;
			
			// aapt resource value: 0x7f070070
			public const int transactionRemarks = 2131165296;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int accountDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int billPaymentScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int branchDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int cardDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int creditCardDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int debitCardDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fundTransfer = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int fundTransferComplete = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int intervalStatement = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int loginScreen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int miniStatement = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int personalDetailsScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int servicesScreen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int signUpScreen = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int transactionScreen = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
